const plants = [
  // Asphalt plants (original scope)
  {
    id: 'apac-memphis',
    type: 'Asphalt Plant',
    company: 'APAC-Tennessee',
    plantName: 'Memphis Asphalt Plant',
    address: '1045 Channel Avenue, Memphis, TN 38113',
    city: 'Memphis',
    county: 'Shelby',
    state: 'TN',
    lat: 35.0829,
    lng: -90.0766,
  },
  {
    id: 'lehman-riverside',
    type: 'Asphalt Plant',
    company: 'Lehman-Roberts',
    plantName: 'Riverside Plant',
    address: '666 Riverside Boulevard, Memphis, TN 38103',
    city: 'Memphis',
    county: 'Shelby',
    state: 'TN',
    lat: 35.1337,
    lng: -90.0665,
  },
  {
    id: 'ford-memphis',
    type: 'Asphalt Plant',
    company: 'Ford Construction Company',
    plantName: 'Memphis Plant',
    address: '2560 Farrisview Boulevard, Memphis, TN 38118',
    city: 'Memphis',
    county: 'Shelby',
    state: 'TN',
    lat: 35.0574,
    lng: -89.9094,
  },
  {
    id: 'lehman-millington',
    type: 'Asphalt Plant',
    company: 'Lehman-Roberts',
    plantName: 'Millington Plant',
    address: '5073 Easley Street, Millington, TN 38053',
    city: 'Millington',
    county: 'Shelby',
    state: 'TN',
    lat: 35.3445,
    lng: -89.8958,
  },
  {
    id: 'apac-covington',
    type: 'Asphalt Plant',
    company: 'APAC-Tennessee',
    plantName: 'Covington Plant',
    address: '1070 U.S. 51 South, Covington, TN 38019',
    city: 'Covington',
    county: 'Tipton',
    state: 'TN',
    lat: 35.548,
    lng: -89.6405,
  },
  {
    id: 'ford-brownsville',
    type: 'Asphalt Plant',
    company: 'Ford Construction Company',
    plantName: 'Brownsville Plant',
    address: '111 Anderson Avenue, Brownsville, TN 38012',
    city: 'Brownsville',
    county: 'Haywood',
    state: 'TN',
    lat: 35.589,
    lng: -89.2616,
  },
  {
    id: 'ford-jackson',
    type: 'Asphalt Plant',
    company: 'Ford Construction Company',
    plantName: 'Jackson Plant',
    address: '1990 Riverside Drive, Jackson, TN 38301',
    city: 'Jackson',
    county: 'Madison',
    state: 'TN',
    lat: 35.6474,
    lng: -88.7994,
  },
  {
    id: 'delta-jackson',
    type: 'Asphalt Plant',
    company: 'Delta Industries',
    plantName: 'Jackson Plant',
    address: '1730 Lower Brownsville Road, Jackson, TN 38301',
    city: 'Jackson',
    county: 'Madison',
    state: 'TN',
    lat: 35.6124,
    lng: -88.876,
  },
  {
    id: 'ford-humboldt',
    type: 'Asphalt Plant',
    company: 'Ford Construction Company',
    plantName: 'Humboldt Plant',
    address: '2550 N. Central Avenue, Humboldt, TN 38343',
    city: 'Humboldt',
    county: 'Gibson',
    state: 'TN',
    lat: 35.8282,
    lng: -88.9037,
  },
  {
    id: 'ford-trenton',
    type: 'Asphalt Plant',
    company: 'Ford Construction Company',
    plantName: 'Trenton Plant',
    address: '415 Industrial Park Drive, Trenton, TN 38382',
    city: 'Trenton',
    county: 'Gibson',
    state: 'TN',
    lat: 35.9726,
    lng: -88.9368,
  },
  {
    id: 'apac-hernando',
    type: 'Asphalt Plant',
    company: 'APAC-Mississippi',
    plantName: 'Hernando Plant',
    address: '1700 Dancy Boulevard, Horn Lake, MS 38637',
    city: 'Horn Lake',
    county: 'DeSoto',
    state: 'MS',
    lat: 34.9649,
    lng: -90.0419,
  },
  {
    id: 'lehman-hernando',
    type: 'Asphalt Plant',
    company: 'Lehman-Roberts',
    plantName: 'Hernando Plant',
    address: '2555 McIngvale Road, Hernando, MS 38632',
    city: 'Hernando',
    county: 'DeSoto',
    state: 'MS',
    lat: 34.8098,
    lng: -89.9908,
  },
  {
    id: 'apac-senatobia',
    type: 'Asphalt Plant',
    company: 'APAC-Mississippi',
    plantName: 'Senatobia Plant',
    address: '1370 Scott Road, Senatobia, MS 38668',
    city: 'Senatobia',
    county: 'Tate',
    state: 'MS',
    lat: 34.6083,
    lng: -89.9553,
  },
  {
    id: 'weblain-sardis',
    type: 'Asphalt Plant',
    company: 'W. E. Blain & Sons',
    plantName: 'Sardis Plant',
    address: '1601 Lee Street, Sardis, MS 38666',
    city: 'Sardis',
    county: 'Panola',
    state: 'MS',
    lat: 34.4367,
    lng: -89.7106,
  },
  {
    id: 'weblain-batesville',
    type: 'Asphalt Plant',
    company: 'W. E. Blain & Sons',
    plantName: 'Batesville Plant',
    address: '141 Eureka Street, Batesville, MS 38606',
    city: 'Batesville',
    county: 'Panola',
    state: 'MS',
    lat: 34.3144,
    lng: -89.9443,
  },
  {
    id: 'apac-oxford',
    type: 'Asphalt Plant',
    company: 'APAC-Mississippi',
    plantName: 'Oxford Plant',
    address: '100 County Road 101, Oxford, MS 38655',
    city: 'Oxford',
    county: 'Lafayette',
    state: 'MS',
    lat: 34.3725,
    lng: -89.4775,
  },
  {
    id: 'falcon-water-valley',
    type: 'Asphalt Plant',
    company: 'Falcon Contracting',
    plantName: 'Water Valley Plant',
    address: '227 CR 278, Water Valley, MS 38965',
    city: 'Water Valley',
    county: 'Yalobusha',
    state: 'MS',
    lat: 34.1566,
    lng: -89.6885,
  },
  {
    id: 'mma-tupelo',
    type: 'Asphalt Plant',
    company: 'Mid-South Materials',
    plantName: 'Tupelo Plant',
    address: '2295 Highway 178 East, Tupelo, MS 38804',
    city: 'Tupelo',
    county: 'Lee',
    state: 'MS',
    lat: 34.289,
    lng: -88.6407,
  },
  {
    id: 'mma-new-albany',
    type: 'Asphalt Plant',
    company: 'Mid-South Materials',
    plantName: 'New Albany Plant',
    address: '402 County Road 58, New Albany, MS 38652',
    city: 'New Albany',
    county: 'Union',
    state: 'MS',
    lat: 34.5136,
    lng: -89.026,
  },
  {
    id: 'weblain-holly',
    type: 'Asphalt Plant',
    company: 'W. E. Blain & Sons',
    plantName: 'Holly Springs Plant',
    address: '1156 Highway 178 West, Holly Springs, MS 38635',
    city: 'Holly Springs',
    county: 'Marshall',
    state: 'MS',
    lat: 34.7667,
    lng: -89.4821,
  },
  {
    id: 'apac-corinth',
    type: 'Asphalt Plant',
    company: 'APAC-Mississippi',
    plantName: 'Corinth Plant',
    address: '1701 Proper Street, Corinth, MS 38834',
    city: 'Corinth',
    county: 'Alcorn',
    state: 'MS',
    lat: 34.9467,
    lng: -88.5222,
  },
  {
    id: 'mma-pontotoc',
    type: 'Asphalt Plant',
    company: 'Mid-South Materials',
    plantName: 'Pontotoc Plant',
    address: '2059 Highway 6 West, Pontotoc, MS 38863',
    city: 'Pontotoc',
    county: 'Pontotoc',
    state: 'MS',
    lat: 34.2478,
    lng: -89.0519,
  },

  // Added aggregate sources
  {
    id: 'memphis-stone-cordova',
    type: 'Limestone Quarry',
    company: 'Vulcan Materials',
    plantName: 'Memphis Stone & Gravel (Cordova Quarry)',
    address: '8116 Macon Road, Cordova, TN 38018',
    city: 'Cordova',
    county: 'Shelby',
    state: 'TN',
    lat: 35.155,
    lng: -89.7745,
  },
  {
    id: 'vulcan-grand-junction',
    type: 'Limestone Quarry',
    company: 'Vulcan Materials',
    plantName: 'Grand Junction Quarry',
    address: '9850 Highway 57, Grand Junction, TN 38039',
    city: 'Grand Junction',
    county: 'Hardeman',
    state: 'TN',
    lat: 35.0577,
    lng: -89.188,
  },
  {
    id: 'mlm-collierville',
    type: 'Sand & Gravel Pit',
    company: 'MLM Aggregates',
    plantName: 'Collierville Sand & Gravel',
    address: '735 Shelton Road, Collierville, TN 38017',
    city: 'Collierville',
    county: 'Shelby',
    state: 'TN',
    lat: 35.0497,
    lng: -89.6589,
  },
  {
    id: 'martin-marietta-rivergate',
    type: 'Sand & Gravel Pit',
    company: 'Martin Marietta',
    plantName: 'Rivergate Sand & Gravel',
    address: '1455 Rivergate Drive, Memphis, TN 38109',
    city: 'Memphis',
    county: 'Shelby',
    state: 'TN',
    lat: 35.0367,
    lng: -90.1168,
  },
  {
    id: 'lehman-olive-branch',
    type: 'Sand & Gravel Pit',
    company: 'Lehman-Roberts',
    plantName: 'Olive Branch Aggregates Yard',
    address: '8100 Hacks Cross Road, Olive Branch, MS 38654',
    city: 'Olive Branch',
    county: 'DeSoto',
    state: 'MS',
    lat: 34.9639,
    lng: -89.7863,
  },
  {
    id: 'vulcan-byhalia',
    type: 'Limestone Quarry',
    company: 'Vulcan Materials',
    plantName: 'Byhalia Quarry',
    address: '2125 Stonewall Road, Byhalia, MS 38611',
    city: 'Byhalia',
    county: 'Marshall',
    state: 'MS',
    lat: 34.8822,
    lng: -89.6673,
  },
  {
    id: 'summit-waterford',
    type: 'Limestone Quarry',
    company: 'Summit Materials',
    plantName: 'Waterford Quarry',
    address: '4700 Highway 4 West, Holly Springs, MS 38635',
    city: 'Holly Springs',
    county: 'Marshall',
    state: 'MS',
    lat: 34.7376,
    lng: -89.6878,
  },
  {
    id: 'north-ms-agg-batesville',
    type: 'Sand & Gravel Pit',
    company: 'North MS Aggregates',
    plantName: 'Batesville Sand Pit',
    address: '2511 Eureka Road, Batesville, MS 38606',
    city: 'Batesville',
    county: 'Panola',
    state: 'MS',
    lat: 34.3317,
    lng: -89.9419,
  },
  {
    id: 'lafayette-crushed-oxford',
    type: 'Limestone Quarry',
    company: 'Lafayette Crushed Stone',
    plantName: 'Oxford North Quarry',
    address: '421 County Road 105, Oxford, MS 38655',
    city: 'Oxford',
    county: 'Lafayette',
    state: 'MS',
    lat: 34.4107,
    lng: -89.4747,
  },
  {
    id: 'union-sand-newalbany',
    type: 'Sand & Gravel Pit',
    company: 'Union County Sand & Gravel',
    plantName: 'New Albany Sand Pit',
    address: '860 County Road 77, New Albany, MS 38652',
    city: 'New Albany',
    county: 'Union',
    state: 'MS',
    lat: 34.5102,
    lng: -89.0126,
  },
  {
    id: 'lee-county-quarry-tupelo',
    type: 'Limestone Quarry',
    company: 'Rogers Group',
    plantName: 'Tupelo Quarry',
    address: '312 Road 681, Tupelo, MS 38804',
    city: 'Tupelo',
    county: 'Lee',
    state: 'MS',
    lat: 34.3073,
    lng: -88.6861,
  },
];
