const plants = [
  {
    id: 'apac-memphis',
    company: 'APAC-Tennessee',
    plantName: 'Memphis Asphalt Plant',
    address: '1045 Channel Avenue, Memphis, TN 38113',
    city: 'Memphis',
    county: 'Shelby',
    state: 'TN',
    lat: 35.0829,
    lng: -90.0766,
  },
  {
    id: 'lehman-riverside',
    company: 'Lehman-Roberts',
    plantName: 'Riverside Plant',
    address: '666 Riverside Boulevard, Memphis, TN 38103',
    city: 'Memphis',
    county: 'Shelby',
    state: 'TN',
    lat: 35.1337,
    lng: -90.0665,
  },
  {
    id: 'ford-memphis',
    company: 'Ford Construction Company',
    plantName: 'Memphis Plant',
    address: '2560 Farrisview Boulevard, Memphis, TN 38118',
    city: 'Memphis',
    county: 'Shelby',
    state: 'TN',
    lat: 35.0574,
    lng: -89.9094,
  },
  {
    id: 'lehman-millington',
    company: 'Lehman-Roberts',
    plantName: 'Millington Plant',
    address: '5073 Easley Street, Millington, TN 38053',
    city: 'Millington',
    county: 'Shelby',
    state: 'TN',
    lat: 35.3445,
    lng: -89.8958,
  },
  {
    id: 'apac-covington',
    company: 'APAC-Tennessee',
    plantName: 'Covington Plant',
    address: '1070 U.S. 51 South, Covington, TN 38019',
    city: 'Covington',
    county: 'Tipton',
    state: 'TN',
    lat: 35.548,
    lng: -89.6405,
  },
  {
    id: 'ford-brownsville',
    company: 'Ford Construction Company',
    plantName: 'Brownsville Plant',
    address: '111 Anderson Avenue, Brownsville, TN 38012',
    city: 'Brownsville',
    county: 'Haywood',
    state: 'TN',
    lat: 35.589,
    lng: -89.2616,
  },
  {
    id: 'ford-jackson',
    company: 'Ford Construction Company',
    plantName: 'Jackson Plant',
    address: '1990 Riverside Drive, Jackson, TN 38301',
    city: 'Jackson',
    county: 'Madison',
    state: 'TN',
    lat: 35.6474,
    lng: -88.7994,
  },
  {
    id: 'delta-jackson',
    company: 'Delta Industries',
    plantName: 'Jackson Plant',
    address: '1730 Lower Brownsville Road, Jackson, TN 38301',
    city: 'Jackson',
    county: 'Madison',
    state: 'TN',
    lat: 35.6124,
    lng: -88.876,
  },
  {
    id: 'ford-humboldt',
    company: 'Ford Construction Company',
    plantName: 'Humboldt Plant',
    address: '2550 N. Central Avenue, Humboldt, TN 38343',
    city: 'Humboldt',
    county: 'Gibson',
    state: 'TN',
    lat: 35.8282,
    lng: -88.9037,
  },
  {
    id: 'ford-trenton',
    company: 'Ford Construction Company',
    plantName: 'Trenton Plant',
    address: '415 Industrial Park Drive, Trenton, TN 38382',
    city: 'Trenton',
    county: 'Gibson',
    state: 'TN',
    lat: 35.9726,
    lng: -88.9368,
  },
  {
    id: 'apac-hernando',
    company: 'APAC-Mississippi',
    plantName: 'Hernando Plant',
    address: '1700 Dancy Boulevard, Horn Lake, MS 38637',
    city: 'Horn Lake',
    county: 'DeSoto',
    state: 'MS',
    lat: 34.9649,
    lng: -90.0419,
  },
  {
    id: 'lehman-hernando',
    company: 'Lehman-Roberts',
    plantName: 'Hernando Plant',
    address: '2555 McIngvale Road, Hernando, MS 38632',
    city: 'Hernando',
    county: 'DeSoto',
    state: 'MS',
    lat: 34.8098,
    lng: -89.9908,
  },
  {
    id: 'apac-senatobia',
    company: 'APAC-Mississippi',
    plantName: 'Senatobia Plant',
    address: '1370 Scott Road, Senatobia, MS 38668',
    city: 'Senatobia',
    county: 'Tate',
    state: 'MS',
    lat: 34.6083,
    lng: -89.9553,
  },
  {
    id: 'weblain-sardis',
    company: 'W. E. Blain & Sons',
    plantName: 'Sardis Plant',
    address: '1601 Lee Street, Sardis, MS 38666',
    city: 'Sardis',
    county: 'Panola',
    state: 'MS',
    lat: 34.4367,
    lng: -89.7106,
  },
  {
    id: 'weblain-batesville',
    company: 'W. E. Blain & Sons',
    plantName: 'Batesville Plant',
    address: '141 Eureka Street, Batesville, MS 38606',
    city: 'Batesville',
    county: 'Panola',
    state: 'MS',
    lat: 34.3144,
    lng: -89.9443,
  },
  {
    id: 'apac-oxford',
    company: 'APAC-Mississippi',
    plantName: 'Oxford Plant',
    address: '100 County Road 101, Oxford, MS 38655',
    city: 'Oxford',
    county: 'Lafayette',
    state: 'MS',
    lat: 34.3725,
    lng: -89.4775,
  },
  {
    id: 'falcon-water-valley',
    company: 'Falcon Contracting',
    plantName: 'Water Valley Plant',
    address: '227 CR 278, Water Valley, MS 38965',
    city: 'Water Valley',
    county: 'Yalobusha',
    state: 'MS',
    lat: 34.1566,
    lng: -89.6885,
  },
  {
    id: 'mma-tupelo',
    company: 'Mid-South Materials',
    plantName: 'Tupelo Plant',
    address: '2295 Highway 178 East, Tupelo, MS 38804',
    city: 'Tupelo',
    county: 'Lee',
    state: 'MS',
    lat: 34.289,
    lng: -88.6407,
  },
  {
    id: 'mma-new-albany',
    company: 'Mid-South Materials',
    plantName: 'New Albany Plant',
    address: '402 County Road 58, New Albany, MS 38652',
    city: 'New Albany',
    county: 'Union',
    state: 'MS',
    lat: 34.5136,
    lng: -89.026,
  },
  {
    id: 'weblain-holly',
    company: 'W. E. Blain & Sons',
    plantName: 'Holly Springs Plant',
    address: '1156 Highway 178 West, Holly Springs, MS 38635',
    city: 'Holly Springs',
    county: 'Marshall',
    state: 'MS',
    lat: 34.7667,
    lng: -89.4821,
  },
  {
    id: 'apac-corinth',
    company: 'APAC-Mississippi',
    plantName: 'Corinth Plant',
    address: '1701 Proper Street, Corinth, MS 38834',
    city: 'Corinth',
    county: 'Alcorn',
    state: 'MS',
    lat: 34.9467,
    lng: -88.5222,
  },
  {
    id: 'mma-pontotoc',
    company: 'Mid-South Materials',
    plantName: 'Pontotoc Plant',
    address: '2059 Highway 6 West, Pontotoc, MS 38863',
    city: 'Pontotoc',
    county: 'Pontotoc',
    state: 'MS',
    lat: 34.2478,
    lng: -89.0519,
  },
];
